x-uffizzi:
  ingress:
    service: dr_py
    port: 8080
services:
  dr_py:
    memory: 4000M
    restart: always
    volumes:
      - share_data:/root/sd/pywork/dr_py
    ports:
      - "5705:5705"
	  - "9001:9001"
    container_name: drpy
    image: esme518/docker-drpy:latest
volumes:
 share_data: